<a href="https://colab.research.google.com/github/yussouf88/Deep_learning/blob/main/My_first_colab_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
2+3

5

In [6]:
import torch
import numpy as np


In [15]:
np1 = np.random.rand(3,4)
np1


array([[0.61360239, 0.68609655, 0.83379173, 0.60845781],
       [0.04036144, 0.40740959, 0.00589867, 0.00320802],
       [0.53543738, 0.61258972, 0.72385416, 0.0306122 ]])

In [17]:
np1.dtype

dtype('float64')

In [23]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.3924, -0.0151, -1.6893,  0.0966],
        [ 1.3246, -0.2460,  1.5407, -0.0045],
        [ 0.4427,  1.0959, -0.5602,  1.1340]])

In [27]:
ten_3d = torch.zeros(2,3,4)
ten_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [30]:
my_ten = torch.tensor(np1)
my_ten

tensor([[0.6136, 0.6861, 0.8338, 0.6085],
        [0.0404, 0.4074, 0.0059, 0.0032],
        [0.5354, 0.6126, 0.7239, 0.0306]], dtype=torch.float64)

In [44]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [49]:
my_torch1 = torch.arange(12)
my_torch1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
my_torch1 = my_torch1.reshape(2,6)
my_torch1

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [56]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [62]:
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
my_torch3 = my_torch3.reshape(3,-1)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [67]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
my_torch1 = my_torch.reshape(2,5)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [72]:
my_torch2 = my_torch.view(2,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
my_torch[1] = 11
my_torch

tensor([ 0, 11,  2,  3,  4,  5,  6,  7,  8,  9])

In [77]:
my_torch1, my_torch2

(tensor([[ 0, 11,  2,  3,  4],
         [ 5,  6,  7,  8,  9]]),
 tensor([[ 0, 11,  2,  3,  4],
         [ 5,  6,  7,  8,  9]]))

In [81]:
my_torch[1]

tensor(11)

In [83]:
my_torch2 = my_torch.reshape(5,2)
my_torch2

tensor([[ 0, 11],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]])

In [95]:
my_torch3 = my_torch2[:,0]
my_torch3

tensor([0, 2, 4, 6, 8])

In [98]:
my_torch3 = my_torch2[1,:]
my_torch3

tensor([2, 3])

In [110]:
my_torch3 = my_torch2[:,1:]
my_torch3

tensor([[11],
        [ 3],
        [ 5],
        [ 7],
        [ 9]])